<?php


namespace App\Controller;

use App\Repository\FaqRepository;
use App\Repository\ServiceRepository;
use App\Repository\EquipeRepository;
use mysql_xdevapi\Table;
use Nadmin\WcmBundle\Entity\Document;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface as Mailer;
use Symfony\Component\Mime\Email;

class DefaultController extends AbstractController
{

    /**
     * @Route("/")
     * @Route("/accueil")
     * @Route("/home")
     */
    public function index(): Response
    {
        return $this->render('templates/accueil.html.twig', [
        ]);
    }

    /**
     * @Route("/services")
     */
    public function services(): Response
    {
        return $this->render('templates/services.html.twig', [
        ]);
    }

    /**
     * @Route("/equipe")
     */
    public function equipes(): Response
    {
        return $this->render('templates/equipes.html.twig', [
        ]);
    }

    /**
     * @Route("/chiens")
     */
    public function chiens(): Response
    {
        return $this->render('templates/chiens.html.twig', [
        ]);
    }

    /**
     * @Route("/admin", name="app_index")
     */
    public function adminIndex(): Response
    {
        return $this->redirectToRoute('wcm_chiens_index');
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/equipe/{url}", name="wcm_equipes_show", methods={"GET"})
     */
    public function Equipe(Request $request,EquipeRepository $equipeRepository, $url): Response
    {
        $service = $equipeRepository->findOneBy(['url' => $url]);
        return $this->render('templates/equipe.html.twig', [
            'equipe' => $service
        ]);
    }

    /**
     * @Route("/services/{url}", name="wcm_services_show", methods={"GET"})
     */
    public function Service(Request $request,ServiceRepository $serviceRepository, $url): Response
    {
        $service = $serviceRepository->findOneBy(['url' => $url]);
        return $this->render('templates/service.html.twig', [
            'service' => $service
        ]);
    }

    /**
     * @Route("/faqs")
     */
    public function faqs(Request $request,FaqRepository $faqRepository): Response
    {
        $faqs = $faqRepository->findAll();
        return $this->render('templates/faqs.html.twig', [
            'faqs' => $faqs
        ]);
    }

    /**
     * @Route("/contact")
     */
    public function contact(Request $request): Response
    {
        return $this->render('templates/contact.html.twig');
    }


//    /**
//     * @Route("/send", methods={"POST"})
//    */
//    public function sendMessage(Request $request, Mailer $mailer): response
//    {
//        $email = (new Email())
//            ->from('lallieechiendassistance@outlook.com')
//            ->to('lallieechiendassistance@outlook.com')
//            ->subject('Formulaire de contact')
//            ->html('<table>
//    <tr><td>$request->get(\'prenom\');</td></tr>
//    <tr><td>$request->get(\'nom\');</td></tr>
//    <tr><td>$request->get(\'email\')</td></tr>
//    <tr><td>$request->get(\'phone\')</td></tr>
//    <tr><td>$request->get(\'message\')</td></tr>
//</table>');
//
//        $mailer->send($email);
//        return $this->render('templates/confirmation.html.twig');
//    }
}


